#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo ':building_construction::builder: Styling, testing and building your project before committing'
npm run format || (
    echo 'Formatting failed, please fix formatting errors before committing'
    false;
)
npm run check-lint || (
    echo 'Linting failed, please fix linting errors before committing'
    false;
)
npm run check-types || (
    echo 'Type checking failed, please fix type errors before committing'
    false;
)
